export const AUTH: string = 'AUTH';
export const AUTHUSER: string = 'AUTHUSER';
export const ALLUSER: string = 'ALLUSER'
export const ALLCHATS: string = 'ALLCHATS';
export const ALLMESSAGE: string = 'ALLMESSAGE';
export const UPDATEMESSAGE: string = 'UPDATEMESSAGE';
export const ADDPOST : string = "ADDPOST";
export const GETALLPOST : string = "GETALLPOST";
export const DELETEPOST : string = "DELETEPOST"
export const LIKEPOST : string = "LIKEPOST"
export const COMMENTPOST : string = "COMMENTPOST"